### ISSUE TITLE
Doesn't work with javascript disabled

### ISSUE THREAD

**Issue by nicklee** [SimonDEvans/front-end-quotes#4]
Please fix

**Comment by SimonDEvans** [comment]
Works for me

**Comment by nicklee** [comment]
Clearly doesn't, please try harder

**Comment by SimonDEvans** [comment]
Please update your browser

**Comment by Loque-** [comment]
it says I need to install the latest version of J-Query but I am pretty sure I have it already, please help my client needs this ASAP!

**Comment by chris-lawton** [comment]
+1

**Comment by nicklee** [comment]
you'd think that with this application being so vital to our workflow that it would just work, but no, again very disappointed with its developer. They should know about the j-query and how important it is to our company.

**Comment by SimonDEvans** [comment]
Would you like to donate to my kickstarter? Maintaining open source projects is very time consuming, especially when meeting the demands of the legacy Long Clawson dependency.

**Comment by indifisher** [comment]
Press F to Pay Respects

**Comment by SimonDEvans** [comment]
If you add more quotes I may consider no-js support.
